### ISSUE TITLE
Possible Typos

### ISSUE THREAD

**Issue by AdrianMarks** [verydanny/iotaGoogleCloudInstance#2]
There are a couple of typos I think need sorting out:
Installing Nelson
Section 4.
should it not read: cat << "EOF" | sudo -u nelson  tee /home/nelson/config.ini
i.e nelson not iota

also 

Section 8. 
should it not read: sudo rm -r /home/iota/node/mainnet.log && sudo rm -r /home/iota/node . . . 
i.e iota not iots

Otherwise an extremely helpful guide - Many Thanks.

**Comment by praveenballa** [comment]
Hi, 

I am getting a "IRI not ready on" error upon running the command

`sudo nelson --config /home/nelson/config.ini
`
Now, I made sure I started the IRI instance using before doing above.

`sudo service iota start`

Any help?

**Comment by verydanny** [comment]
@AdrianMarks 
1. You're right, fixed. Also realized nelson is installed globally and therefore can only really be run by sudo, so the `-u nelson` isn't really needed unless I changed NPM's global install directory. I may add that to the tutorial soon.
2. I removed the section on deleting the database, etc.

@praveenballa 
Please create separate issues for new problems :) Also, that means IRI isn't "booted up" yet, just be patient. If it has to rescan the db, it takes up to 2 hours.

**Comment by AdrianMarks** [comment]
@verydanny 

Don't forget to also update the  README.md not just the wiki. 

Best regards
